(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var E4=function(a){a.ma("cardstatechange",a.zi()&&a.tm()?1:0)},F4=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},$0a=function(a){var b=g.Gl(a);
a=g.Jl(a);return new g.vl(b.x,b.y,a.width,a.height)},a1a=function(a){return Math.pow(a,3)},b1a=function(a){return 3*a*a-2*a*a*a},I4=function(a){a=g.Pa(a);
delete G4[a];g.Df(G4)&&H4&&H4.stop()},d1a=function(){H4||(H4=new g.Zn(function(){c1a()},20));
var a=H4;a.isActive()||a.start()},c1a=function(){var a=g.Va();
g.mf(G4,function(b){e1a(b,a)});
g.Df(G4)||d1a()},J4=function(a,b,c,d){g.to.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},e1a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;f1a(a,a.progress);1==a.progress?(a.j=0,I4(a),a.onFinish(),a.Vz()):a.Sc()&&a.rF()},f1a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},g1a=function(a,b){g.cf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},K4=function(a,b,c,d,e){J4.call(this,b,c,d,e);
this.element=a},h1a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K4.call(this,a,b,c,d,e)},L4=function(a){g.J.call(this);
this.u=a||window;this.j=[]},M4=function(a){return a.baseUrl||null},N4=function(a,b){return g.xm(g.Pk(a,b),function(c){return!!c})},i1a=function(a,b,c){function d(X){var Q=X.hovercardButton;
if(!Q)return null;Q=Q.subscribeButtonRenderer;if(!Q)return null;var oa=f(Q.unsubscribedButtonText),ta=f(Q.subscribedButtonText);if(Q.subscribed){var Ba=f(Q.subscriberCountWithUnsubscribeText);var ya=f(Q.subscriberCountText)}else Ba=f(Q.subscriberCountText),ya=f(Q.subscriberCountWithSubscribeText);var ua=null;if(X.signinEndpoint){ua=F4(X,"signinEndpoint","webNavigationEndpointData","url");if(!ua){var Ja,Ka,qa;ua=null==(Ja=Q.signInEndpoint)?void 0:null==(Ka=Ja.commandMetadata)?void 0:null==(qa=Ka.webCommandMetadata)?
void 0:qa.url}if(!ua)return null}return oa&&(ta||ua)?{subscribed:Q.subscribed,subscribeText:oa,subscribeCount:Ba,unsubscribeText:ta,unsubscribeCount:ya,enabled:Q.enabled,signinUrl:ua,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var Q=[],oa=X.videoId;oa&&Q.push("v="+oa);(oa=X.playlistId)&&Q.push("list="+oa);(X=X.startTimeSeconds)&&Q.push("t="+X);return"/watch?"+Q.join("&")}}
function f(X){if(!X)return null;var Q=X.simpleText;return Q?Q:X.runs?g.Pk(X.runs,function(oa){return oa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,u=null,w=null,y=null,A=!1,B=null,D=null,F=null,H=null,L=null,N=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(N=l.watchEndpoint,m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,u=f(p.text),p="LIVE"===p.style):u=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(N=l.watchEndpoint,m=e(N)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(A=F4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?B=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((F=F4(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=F4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F4(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:
null,P="";if(b.metadata){var S=f(b.metadata);S&&(P=S)}return{id:"element-"+c,type:h,title:f(b.title),metadata:P,callToAction:f(b.callToAction),BO:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:u,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:D,isSubscribe:A,targetUrl:m||null,f_:n,sessionData:K?{itct:K}:null,B5:q,Tx:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:N4(b.impressionUrls||[],M4),QZ:N4(b.hovercardShowUrls||[],M4),clickUrls:N4(l.loggingUrls||[],M4),visualElement:g.wz(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},j1a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N4(a.impressionUrls||[],M4),elements:N4(a.elements||[],function(d,e){return i1a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.wz(a.trackingParams));return c},k1a=function(a){g.fO.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.S=g.VF(a)||g.ZF(a);this.ea=a.experiments.jb("web_rounded_thumbnails");this.events=new g.aE(this);g.M(this,this.events);this.events.T(this.player,g.wA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.xA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Ab);this.events.T(window,"focus",this.F3);this.load();var b=g.ih("STYLE");(g.ah("HEAD")[0]||
document.body).appendChild(b);g.bf(this,function(){g.sh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},l1a=function(a){return a.player.getVideoData().C?"current":a.S?"new":"current"},O4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},m1a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=j1a(f,l1a(a))));P4(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Yq;d&&(c.postParams={ad_tracking:d});if(b=g.PBa(b))if(b=g.pg(b),b=g.og(b))a.B=g.Eu(b,c)},P4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ff("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&n1a(a);c=[];d=new g.uA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({F:"div",N:"ytp-ce-shadow"}),g.EN(a.player,a.u.element,4),a.C=new g.ML(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=o1a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.EN(a.player,f.element,4);var h=new g.uA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);p1a(a,
f,e)}else g.tz(new g.Tv("buildEndscreenElement null",e))}a.player.qe(c);a.Ab()}},n1a=function(a){var b=g.Cz(),c=g.Dz();
c&&b&&a.endscreen.visualElement&&g.Hz(void 0,c,b,[a.endscreen.visualElement])},o1a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Tx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:Q4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.xo(b.title||"")},qa:b.title},{F:"div",N:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Tx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:Q4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.xo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-playlist-count",
W:[{F:"div",N:"ytp-ce-playlist-icon"},{F:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Tx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.xo(b.title||"")},qa:b.title},b.subscribeButton?{F:"div",N:"ytp-ce-subscribe-container",W:[{F:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{F:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)}]};c=new g.W(c);var d=g.bh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.ho(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.jP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Tx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-website-title",X:{dir:g.xo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)},{F:"div",N:"ytp-ce-expanding-icon",X:q1a(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",N:"ytp-ce-merchandise-price-container",W:[{F:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={F:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Tx||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},
{F:"div",N:"ytp-ce-expanding-overlay-content",W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-merchandise-title",X:{dir:g.xo(b.title||"")},qa:b.title},c,{F:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)},{F:"div",N:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",N:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.ho(c.element,"ytp-ce-placeholder");return c},Q4=function(a){if(a.BO)var b=a.BO.thumbnails;
return q1a(b?b[b.length-1].url:null)},q1a=function(a){return a?{style:"background-image: url("+a+")"}:{}},p1a=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.ho(b.element,"ytp-ce-force-expand"),S4(a,c.id,!0)):(g.jo(b.element,"ytp-ce-force-expand"),g.jo(b.element,"ytp-ce-element-hover"),S4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){r1a(a,b,c)});
b.Ra("mouseleave",function(){s1a(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.ho(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){t1a(a,c,m)});
b.Ra("keypress",function(m){t1a(a,c,m)});
b.Ra("focus",function(){r1a(a,b,c)});
b.Ra("blur",function(){s1a(a,b,c)});
b.Ra("touchstart",function(){r1a(a,b,c)});
var l=g.dh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.jo(b.element,"ytp-ce-element-hover");g.jo(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.dh("ytp-sb-subscribe",b.element));d(g.dh("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},t1a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.go(d,"ytp-ce-element");){g.go(d,"subscribe-label")&&u1a(a,b);
if(g.go(d,"ytp-ce-channel-subscribe"))return;d=g.th(d)}if(!d||g.go(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])s1a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.B5)u1a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.pg(R4(a,b.targetUrl)),g.mM(g.og(c),void 0,b.sessionData);else{var e=g.oG(a.player.V())||a.player.getVideoData().C,f=function(){var h=R4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.pu(h);e&&n&&(n.v||
n.list)?a.player.Ll(n.v,l,n.list,!1,void 0,m||void 0):g.lM(h,l)};
u1a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},R4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.yG(a)+b}else return"";return b},r1a=function(a,b,c){g.go(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.ho(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.Zn(function(){g.ho(b.element,"ytp-ce-element-hover")},200)).start():g.ho(b.element,"ytp-ce-element-hover"),T4(a,c.QZ),S4(a,c.id,!0))},s1a=function(a,b,c){g.jo(b.element,"ytp-ce-element-hover");
g.jo(b.element,"ytp-ce-force-expand");S4(a,c.id,!1)},S4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.lo(a.j[e].element,"ytp-ce-element-shadow-show",c)},T4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||O4(a))c&&c();else{b=v1a(a,b);var e=0,f=!1,h=new g.Zn(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Yw(b[a],d)}},u1a=function(a,b,c){T4(a,b.clickUrls,c);
(a=g.Dz())&&b.f_&&g.Nz(a,b.visualElement)},v1a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(w1a(b[d],c));return a},w1a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},x1a=function(a){return"string"===typeof a?a:""},U4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},y1a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},V4=function(a){return a.value?a.value:null},W4=function(a){if(!a)return null;
var b=g.pg(x1a(a.value));b=g.og(b);if(!b)return null;var c=U4(a.target,z1a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new y1a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},A1a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},D1a=function(a){if(!a)return null;
var b=U4(a.type,B1a),c=U4(a.trigger,C1a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W4(a?a:null);return b?new A1a(b,c,a):null},E1a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},F1a=function(a,b){return g.Sb(a.action,b)},G1a=function(a,b){this.context=a;
this.j=b},H1a=function(a){return a.customMessage?X4("div","iv-card-message",a.customMessage):""},Y4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",N:"iv-card-image",X:{style:a},W:c}},I1a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X4("li","",c.value));return{F:"ul",N:"iv-card-meta-info",W:b}},X4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.xo(c);return{F:a,X:b,qa:c}},J1a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.iy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.iy+");");c.dir=g.xo(a.customMessage);var d=[{F:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",N:"iv-card-link-icon"}));return{F:"div",Ga:b,X:c,W:d}},Z4=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},K1a=function(a,b){this.merchant=a;
this.price=b},L1a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},M1a=function(a,b){return b?b:L1a(a)?"current":"new"},$4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.yb=!1;this.Ya=new Map;this.eb=new Map;this.context.G.addEventListener(g.wA("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.xA("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},a5=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.sF(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.yb=!1});
a.context.j.Ra(b,"touchmove",function(){a.yb=!0})},N1a=function(a){var b;
return(null==(b=g.cv(a,g.UH))?0:b.url)?g.cv(a,g.UH).url:(a=g.cv(a,g.YG))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},b5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
NS:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
FE:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},O1a=function(a,b,c){$4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Qa=this.Rb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Fb=this.S=this.La=this.D=this.Va=this.j=null;this.ea=[];this.oa=this.J=this.sf=this.Ia=null;this.I=0;this.Ba=new g.Zn(function(){},c.Y.kf?4E3:3E3);
g.M(this,this.Ba);this.ob=new g.Zn(function(){});
g.M(this,this.ob);this.Aa=new G1a(c,function(e,f,h,l,m,n){a5(d,e,f,h,l,m,n)});
this.Z=new g.W({F:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",N:"iv-drawer-header-text"},{F:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",tabindex:"0"}}]},{F:"div",N:"iv-drawer-content"}]});g.M(this,this.Z);this.C=this.Z.element;this.kb=new g.ML(this.Z,330);g.M(this,this.kb);this.Kb=g.dh("iv-drawer-header-text",this.C);
this.u=g.dh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Rb&&c5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&d5(d)});
this.G.addEventListener("videodatachange",this.Yp.bind(this))},P1a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){c5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){d5(a)});
var c=b.headerText;g.vh(a.Kb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.wz(b.trackingParams);a.J=g.wz(b.closeTrackingParams);a.sf=g.wz(b.iconTrackingParams)},Q1a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},wm:null,Dj:e.trackingParams?g.wz(e.trackingParams):null,sf:f&&f.trackingParams?g.wz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,iy:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};e5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.BA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,f),sponsored:!1,tracking:b5(f,e,f.command),wm:f.trackingParams?g.wz(f.trackingParams):null,Dj:e.trackingParams?g.wz(e.trackingParams):null,sf:l&&l.trackingParams?g.wz(l.trackingParams):null,imageUrl:g5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.BA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,iy:null,title:f.title?g.BA(f.title):"",customMessage:f.callToAction?g.BA(f.callToAction):"",url:g.cv(f.command,g.UH).url?W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.cv(f.command,g.UH).url}):null,onClickCommand:null};e5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.BA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.endpoint),wm:e.trackingParams?g.wz(e.trackingParams):null,Dj:f.trackingParams?g.wz(f.trackingParams):null,sf:l&&l.trackingParams?g.wz(l.trackingParams):null,channelId:g.cv(e.endpoint,h5).browseId,customMessage:e.customText?g.BA(e.customText):null,profileImageUrl:g5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.BA(e.channelName):"",metaInfo:[e.subscriberCountText?g.BA(e.subscriberCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.cv(e.endpoint,h5).canonicalBaseUrl?g.cv(e.endpoint,h5).canonicalBaseUrl:"/channel/"+g.cv(e.endpoint,h5).browseId}),onClickCommand:null};e5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.BA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),wm:e.trackingParams?g.wz(e.trackingParams):null,Dj:f.trackingParams?g.wz(f.trackingParams):null,sf:l&&l.trackingParams?g.wz(l.trackingParams):null,LA:g5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.BA(e.customMessage):null,playlistVideoCount:g.BA(e.playlistVideoCount),title:e.playlistTitle?g.BA(e.playlistTitle):"",metaInfo:[e.channelName?
g.BA(e.channelName):"",e.videoCountText?g.BA(e.videoCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:N1a(e.action)}),onClickCommand:null};e5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.BA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),wm:e.trackingParams?g.wz(e.trackingParams):null,Dj:f.trackingParams?g.wz(f.trackingParams):null,sf:l&&l.trackingParams?g.wz(l.trackingParams):null,LA:g5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.BA(e.lengthString):null,customMessage:e.customMessage?g.BA(e.customMessage):null,title:e.videoTitle?g.BA(e.videoTitle):"",metaInfo:[e.channelName?
g.BA(e.channelName):"",e.viewCountText?g.BA(e.viewCountText):""],isLiveNow:!!e.badge,url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:N1a(e.action)}),onClickCommand:null};e5(a,b)}}}}}a.I++},g5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},f5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},S1a=function(a,b){if(b=R1a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.sh(b.OG),g.Zb(a.cards,b),a.LB(),i5(a)},c5=function(a,b,c){if(!a.B){a.kb.show();
a.Va=new g.Zn(function(){g.ho(a.context.G.getRootNode(),g.sT.IV_DRAWER_OPEN)},0);
a.Va.start();a.ya=g.Cx(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Dz();d&&a.Ia&&a.J&&g.Lz(d,[a.Ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.lQ||(f.lQ=!0,T1a(a.context.logger,f.card.tracking.impression,b)),d&&g.Lz(d,[f.card.wm]);E4(a.G);c&&(a.D=new g.Zn(function(){a.La=a.S;a.Fb.focus()},330),a.D.start())}},d5=function(a){a.B&&(a.kb.hide(),g.Dx(a.ya),a.ya=null,g.jo(a.context.G.getRootNode(),g.sT.IV_DRAWER_OPEN),a.B=!1,E4(a.G),a.D&&a.D.stop(),a.D=new g.Zn(function(){a.La&&(a.La.focus(),a.La=null)},330),
a.D.start())},V1a=function(a){g.io(a.element,[g.sT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.EN(a.G,a.C,5);U1a(a);a.S=g.dh("ytp-cards-button",a.G.getRootNode());a.Fb=g.dh("iv-drawer-close-button",a.C);a.isInitialized=!0},U1a=function(a){var b=g.dh("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.eY,a);a.context.j.Ra(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Ra(a.u,"scroll",a.xY,a);a.context.u.subscribe("onHideControls",function(){a.Qa=!0});
a.context.u.subscribe("onShowControls",function(){a.Qa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Qa=g.go(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.Wx("iv-button-shown",a.r_,a));a.ea.push(g.Wx("iv-button-hidden",a.q_,a));a.ea.push(g.Wx("iv-teaser-shown",a.sU,a));a.ea.push(g.Wx("iv-teaser-hidden",a.t_,a));a.ea.push(g.Wx("iv-teaser-clicked",a.rU,a))},W1a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.cv(b.onClickCommand,g.$Ya))?void 0:c.targetId)?(a.oa=b,!0):!1},X1a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.cv(h[0],g.x_a))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}}a.oa=b;return!1},e5=function(a,b){if(!W1a(a,b)||X1a(a,b)){var c=Y1a(a,b);
if(c){var d={card:b,OG:c.element,lQ:!1};if(!b.onClickCommand){a.isInitialized||V1a(a);S1a(a,b.id);var e=Z1a(a,d);g.hc(a.cards,e,0,d);c.Ca(a.u,e);a.LB()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,i5(a),$1a(a,d),c5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&a2a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){a2a(a,d)}),i5(a))}}},Y1a=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{F:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=J1a(b);d={F:"div",Ga:["iv-card"],W:[{F:"a",N:"iv-click-target",X:{href:b.url?V4(b.url)||"":""},W:[Y4(b.imageUrl,d),{F:"div",N:"iv-card-content",W:[X4("h2",void 0,b.title),e]}]}]};d=new g.W(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-channel"],W:[{F:"a",Ga:["iv-click-target"],X:{href:V4(b.url)||"","data-ytid":b.channelId},W:[Y4(b.profileImageUrl),
{F:"div",N:"iv-card-content",W:[H1a(b),{F:"h2",N:"iv-card-primary-link",qa:b.title},I1a(b)]}]}]};d=new g.W(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-playlist"],W:[{F:"a",N:"iv-click-target",X:{href:V4(b.url)||""},W:[Y4(b.LA,{F:"div",N:"iv-card-image-overlay",W:[{F:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{F:"div",N:"iv-card-content",W:[H1a(b),X4("h2","iv-card-primary-link",b.title),I1a(b)]}]}]};
d=new g.W(d);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.Vb(b.offers);d=["iv-card"];e="";var h=J1a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",N:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({F:"div",N:"iv-card-offer-merchant",qa:h.merchant}),h={F:"div",W:f});f=b.url?V4(b.url)||"":"";d={F:"div",Ga:d,X:{tabindex:"0"},W:[{F:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",N:"iv-card-content",W:[b.sponsored?{F:"div",N:"iv-card-sponsored",W:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{F:"div",N:"iv-ad-info-container",W:[{F:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{F:"div",N:"iv-ad-info-icon-container",W:[{F:"div",N:"iv-ad-info-icon"},{F:"div",N:"iv-ad-info-callout"}]}]}]}:"",{F:"a",N:"iv-click-target",X:{href:f},W:[X4("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.ih("span");g.vh(e,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
d.Vd(e,"adInfo");Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{F:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ga:["yt-badge","yt-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:null;f={F:"div",Ga:["iv-card","iv-card-video"],W:[{F:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:V4(h))||""},W:[Y4(b.LA,d),{F:"div",N:"iv-card-content",
W:[H1a(b),X4("h2","iv-card-primary-link",b.title),I1a(b),e]}]}]};d=new g.W(f);Z4(c,g.ch("iv-click-target",d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.jb("web_rounded_containers")&&g.ho(b.element,"ytp-rounded-info");return b},Z1a=function(a,b){if(0===a.cards.length)return 0;
a=g.Tb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},b2a=function(a){return a.j?"productListing"===a.j.card.type:g.Yd(a.cards,function(b){return"productListing"===b.card.type})},i5=function(a){g.lo(a.G.getRootNode(),"ytp-cards-shopping-active",b2a(a))},a2a=function(a,b){if(!g.go(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Dz(),d=a.j?a.j.card.sf:a.sf;
c&&d&&g.Mz(c,[d]);a.j=b;i5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Qw(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ob.isActive()||((!a.B||!a.Ba.isActive()&&a.Qa)&&$1a(a,b),a.ob.start(910+b.card.teaserDurationMs))}},$1a=function(a,b){a.Z.rb?(b=new J4([0,
a.u.scrollTop],[0,b.OG.offsetTop],600,b1a),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.aL(a.Z,!0),a.u.scrollTop=b.OG.offsetTop,g.aL(a.Z,!1))},j5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},R1a=function(a,b){return g.Sb(a.cards,function(c){return c.card.id===b})},k5=function(a,b,c){$4.call(this,a,b);
this.annotation=c;this.isActive=!1},c2a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l5=function(a,b,c){k5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},d2a=function(a,b){var c=void 0===c?0:c;
var d=$0a(b).width;g.El(b,d);c=new h1a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,a1a);g.M(a,c);a.context.B.Ra(c,"begin",function(){g.Kl(b,!0)});
c.play()},g2a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({F:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.jP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Kl(h,!1);a.context.Y.K("web_rounded_containers")&&g.ho(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.yl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.Zn(function(){e2a(a,h,l)},500);
g.M(a,a.B);a.context.j.Ra(a.element,"mouseover",function(){f2a(a,h,l,f,b.image_height)});
a.context.j.Ra(a.element,"mouseout",function(){a.B.start()})}},f2a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Jl(b);a.j||(b.style.width=g.Dl(f.width,!0),c.style.width=g.Dl(f.width,!0));g.yl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.yl(d,"right","1px");a.C=!0;g.Kl(b,!0);a.D=new g.Zn(function(){g.ho(this.element,"iv-branding-active")},0,a);
a.D.start()}},e2a=function(a,b,c){g.jo(a.element,"iv-branding-active");
a.I=new g.Zn(function(){g.Kl(b,!1);a.j||(c.style.width=g.Dl(0,!0))},250);
a.I.start();a.C=!1},h2a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},i2a=function(a,b,c){k5.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ga:["iv-promo-contents"]});this.D=new g.Zn(function(){d.j.setAttribute("aria-hidden","true");g.Kl(d.B,!1);g.Kl(d.u,!0)},700,this);
g.M(this,this.D)},k2a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");a.element.tabIndex=0;var e=a.annotation.ye(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,
"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=a.createElement({F:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&a5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",N:"iv-promo-txt"}),g.Dg(f,V4(e)),a.j=f):a.j=a.createElement({F:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=
a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ga:["iv-button","iv-promo-button"],W:[{F:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({F:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&a5(a,a.element,e,a.annotation.id,
b.session_data,void 0,c)}g.ho(a.j,"iv-click-target");e&&a5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",qa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"})),g.ho(a.j,"iv-click-target"),e&&a5(a,
a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);c=a.createElement({F:"div",N:"iv-promo-actions"});a.u=a.createElement({F:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";a.context.j.Ra(a.u,"click",function(q){j2a(a,5E3,q)});
c.appendChild(a.u);g.Kl(a.u,!1);a.context.j.Ra(a.element,"mouseover",a.tZ,a);a.context.j.Ra(a.element,"mouseout",a.sZ,a);a.context.j.Ra(a.element,"touchend",function(q){j2a(a,5E3,q)});
a.B=a.createElement({F:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.oZ:a.nZ,a);c.appendChild(a.B);g.io(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},j2a=function(a,b,c){c.stopPropagation();
l2a(a);m2a(a,b);a.j.focus()},n2a=function(a){a.isCollapsed||a.S||a.C||(g.ho(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},l2a=function(a){a.D.stop();
a.isCollapsed&&(g.ko(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Kl(a.u,!1),g.Kl(a.B,!0))},m2a=function(a,b){a.C||(a.C=g.Qh(function(){o2a(this);
n2a(this)},b,a))},o2a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},p2a=function(a){this.G=a},T1a=function(a,b,c){b&&(c?m5(a,b.map(function(d){return g.Sn(d,c)})):m5(a,b))},m5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Yw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},q2a=function(a){g.fO.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new p2a(this.player);this.D=new g.aE(this);this.C=this.En=null;this.events=new g.aE(this);this.J=this.j=null;this.S=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ma("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.tU,this);this.subscribe("resize",this.ED,this);this.player.V().oa.subscribe("vast_info_card_add",this.xR,this);g.M(this,this.events);this.Z=this.createElement({F:"div",N:"video-custom-annotations"});this.u=new g.W({F:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.u);g.EN(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Ga:["ytp-iv-video-content"]});g.M(this,this.B);a=this.createElement({F:"div",N:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Qt()&&this.load();var c=this.createElement({F:"style"});(g.ah("HEAD")[0]||document.body).appendChild(c);g.bf(this,function(){g.sh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},r2a=function(a){a=a.createElement({F:"div",
Ga:["annotation","annotation-type-custom"]});g.Kl(a,!1);return a},s2a=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.aL(a.u,b);g.aL(a.B,b)},t2a=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(t2a(a,e))}return c},x2a=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.V().oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.yu(h)&&h.responseXML?h.responseXML:null)&&u2a(a,h)}};
g.Hv()&&(d.onFinish=v2a(a,d.onFinish));d.postParams={ic_only:"1"};w2a(d,c);g.Eu(b.Ya,d)}}},w2a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.jy&&(a.postParams.ic_coll=b.jy);b.RB&&(a.postParams.ic_xml=b.RB);b.PA&&(a.postParams.ic_track=b.PA)},y2a=function(a){var b=new g.W({F:"div"});
g.Kl(b.element,!1);var c=new O1a(a.player,b.element,n5(a));g.M(c,b);b.Ca(a.u.element);c.zA();return c},n5=function(a){if(!a.J){var b=new L4(a);
g.M(a,b);var c=new g.Rj(a);g.M(a,c);a.J=new h2a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.xg)}return a.J},u2a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Dz();if(e){var f=g.Cz();f&&g.Hz(void 0,e,f,[g.wz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=t2a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U4(f.type,z2a),p=U4(f.style,A2a),q=x1a(f.data),u=0!==q.length?JSON.parse(q):{};var w=f.action;f=D1a;if(null==w)var y=null;else if(g.Ma(w)){l=[];for(var A=g.r(w),B=A.next();!B.done;B=A.next()){var D=f(B.value);
D&&l.push(D)}y=l}else{var F=f(w);y=F?[F]:[]}e=m&&n?new E1a(m,n,p,y,u):null}else e=null}catch(S){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=r2a(f),L=null;switch(l.type){case "branding":if(f.player.V().Rc)break;f.u.element.appendChild(H);L=new l5(H,n5(f),l);break;case "promotion":g.EN(f.player,H,4),L=new i2a(H,n5(f),l)}L&&L.zA();if(f=L)g.M(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=y2a(a),g.M(a,a.j));if("card"===e.type){c=a.j;var N=e&&e.data&&e.data.card_type;
f=e.data;if(N)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,NS:l.teaser_impression,FE:l.teaser_click},H=f.tracking_params||{},L=null,N){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,wm:H.card?g.wz(H.card):null,Dj:H.teaser?g.wz(H.teaser):null,sf:H.icon?g.wz(H.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
wm:H.card?g.wz(H.card):null,Dj:H.teaser?g.wz(H.teaser):null,sf:H.icon?g.wz(H.icon):null,LA:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "productListing":f.signin_url&&(L=W4({target:"current",value:f.signin_url}));N=[];for(var K=f.offers||[],P=0;P<K.length;P++)N.push(new K1a(g.Vg(K[P].merchant),
g.Vg(K[P].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,wm:H.card?g.wz(H.card):null,Dj:H.teaser?g.wz(H.teaser):null,sf:H.icon?g.wz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),b6a:L,a6a:f.signin_title?f.signin_title:void 0,Z5a:f.signin_message?f.signin_message:void 0,offers:N,onClickCommand:null};e5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,wm:H.card?g.wz(H.card):
null,Dj:H.teaser?g.wz(H.teaser):null,sf:H.icon?g.wz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,wm:H.card?g.wz(H.card):null,Dj:H.teaser?g.wz(H.teaser):null,sf:H.icon?g.wz(H.icon):null,LA:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},e5(c,e)}}else P1a(a.j,e);c=
!0}}c&&(E4(a.player),a.ED())},B2a=function(a,b){var c=!1;
a.j||(a.j=y2a(a),g.M(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Q1a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.BA(b.headerText):"",g.vh(c.Kb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.wz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.wz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.sf=b.icon.infoCardIconRenderer.trackingParams?
g.wz(b.icon.infoCardIconRenderer.trackingParams):null,E4(a.player),a.ED())},C2a=function(a,b,c,d,e){if(!a.player.V().Rc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new A1a("openUrl","click",new y1a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.BA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.BA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.BA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.BA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.BA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.BA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new E1a(c,"branding","branding",f,d);l=r2a(a);a.u.element.appendChild(l);f=new l5(l,n5(a),f);f.zA();g.M(f,f);a.I[c]=f}},v2a=function(a,b){return function(){var c=
g.za.apply(0,arguments);
a.isDisposed()||a.S.push(g.Vn.Jh(function(){b.apply(null,g.t(c))}))}},D2a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.xN.prototype.Qw=g.ba(17,function(a,b){var c=g.xO(this.tb());c&&c.Qw(a,b)});
var G4={},H4=null;g.Wa(J4,g.to);g.k=J4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Sc())return!1;I4(this);this.startTime=a=g.Va();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.AD();this.Yj("play");-1==this.j&&this.Yj("resume");this.j=1;var b=g.Pa(this);b in G4||(G4[b]=this);d1a();e1a(this,a);return!0};
g.k.stop=function(a){I4(this);this.j=0;a&&(this.progress=1);f1a(this,this.progress);this.Yj("stop");this.Vz()};
g.k.pause=function(){this.Sc()&&(I4(this),this.j=-1,this.Yj("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Yj("destroy");J4.Qe.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.rF=function(){this.Yj("animate")};
g.k.Yj=function(a){this.dispatchEvent(new g1a(a,this))};
g.Wa(g1a,g.cf);g.Wa(K4,J4);K4.prototype.C=function(){};
K4.prototype.rF=function(){this.C();K4.Qe.rF.call(this)};
K4.prototype.Vz=function(){this.C();K4.Qe.Vz.call(this)};
K4.prototype.AD=function(){this.C();K4.Qe.AD.call(this)};
g.Wa(h1a,K4);h1a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var h5=new g.Zo("browseEndpoint");g.v(L4,g.J);L4.prototype.Ra=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Cx(a,b,c);this.j.push(a);return a};
L4.prototype.kD=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Goa(a,b,c);this.j.push(a);return a};
L4.prototype.yc=function(a){g.Dx(a);g.Zb(this.j,a)};
L4.prototype.ra=function(){g.Dx(this.j);this.j.length=0;g.J.prototype.ra.call(this)};g.v(k1a,g.fO);g.k=k1a.prototype;g.k.load=function(){g.fO.prototype.load.call(this);if(!O4(this)){var a=g.QBa(this.player.getVideoData());a?(a=j1a(a,l1a(this)),P4(this,a,!1)):m1a(this)}};
g.k.unload=function(){P4(this,null);this.B&&(this.B.abort(),this.B=null);g.fO.prototype.unload.call(this)};
g.k.Cg=function(a,b){return O4(this)?"loadCustomEndscreenRenderer"===a?(a=j1a(b,"new"),P4(this,a),!0):null:null};
g.k.getOptions=function(){return O4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ab=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<E2a.length;f++){var h=Math.abs(b.width-E2a[f]);if(-1===e||d>=h)e=f,d=h}d=F2a[e];this.u&&g.yl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Il(e.element,m,f);g.El(e.element,n,p);this.ea&&(g.ko(e.element,G2a),256<m||256<f?g.ho(e.element,"ytp-ce-large-round"):96<m||96<f?g.ho(e.element,"ytp-ce-medium-round"):g.ho(e.element,"ytp-ce-small-round"));g.ko(e.element,H2a);m=h.left+h.width/2;h=h.top+l/2;g.ho(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ko(e.element,F2a);g.ho(e.element,d);(e=g.bh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.yl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T4(this,this.endscreen.impressionUrls),(a=g.Dz())&&this.endscreen.visualElement&&g.Iz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.ho(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.ho(b,"ytp-ce-shown");T4(this,c.impressionUrls);(b=g.Dz())&&g.Iz(b,c.visualElement);this.player.V().C&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.jo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.jo(b,"ytp-ce-shown");this.player.V().C&&this.player.Pa("endscreenelementhidden",a)}};
g.k.F3=function(a){var b=this;a.target===window&&(new g.Zn(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.ko(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var E2a=[346,426,470,506,570,640,853,1280,1920],F2a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),H2a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],G2a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var z1a={jla:"current",SHa:"new"};var B1a={CLOSE:"close",sLa:"openUrl",SUBSCRIBE:"subscribe"},C1a={rga:"click",CLOSE:"close",Iua:"hidden",CQa:"rollOut",DQa:"rollOver",vSa:"shown"};E1a.prototype.ye=function(){var a=F1a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var A2a={fca:"anchored",RT:"branding",CHANNEL:"channel",Xka:"cta",Lua:"highlightText",vya:"label",PLAYLIST:"playlist",kOa:"popup",YUa:"speech",SUBSCRIBE:"subscribe",UXa:"title",VIDEO:"video",k3a:"website"},z2a={RT:"branding",uea:"card",lna:"drawer",Kua:"highlight",VDa:"marker",kPa:"promotion",TEXT:"text",S3a:"widget"};g.v($4,g.J);g.k=$4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.uA(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.eb.set(a,e);this.context.G.qe([a])};
g.k.zA=function(){this.context.u.subscribe("resize",this.LB,this)};
g.k.sF=function(a,b,c,d,e,f){if(this.yb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.sh(this.element)};
g.k.LB=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V4(a);if(f){var h=M1a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.pu(f||"");m&&n&&(n.v||n.list)?e.context.G.Ll(n.v,b,n.list,!1):g.mM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m5(this.context.logger,c,l,d);L1a(f)||(c=g.Dz(),d=b.itct,c&&d&&g.Nz(c,g.wz(d)))}};
g.k.ra=function(){this.Ya.clear();this.eb.clear();g.J.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.v(O1a,$4);g.k=O1a.prototype;g.k.Yp=function(){this.oa&&e5(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Jl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.LB=function(){var a=this.isAvailable();g.Kl(this.element,a);g.lo(this.context.G.getRootNode(),g.sT.IV_DRAWER_ENABLED,a);E4(this.G)};
g.k.destroy=function(){this.G.Qw(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Xx(this.ea);g.Dx(this.ya);this.Va&&this.Va.dispose();this.D&&this.D.dispose();$4.prototype.destroy.call(this)};
g.k.eY=function(){if(this.B){m5(this.context.logger,j5(this).tracking.close);var a=g.Dz();a&&this.J&&g.Nz(a,this.J);d5(this)}};
g.k.xY=function(){g.lo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.r_=function(){var a=g.Dz(),b=j5(this);b=b?b.sf:this.sf;a&&b&&g.Lz(a,[b])};
g.k.q_=function(){var a=g.Dz(),b=j5(this);b=b?b.sf:this.sf;a&&b&&g.Mz(a,[b])};
g.k.sU=function(){var a=j5(this);m5(this.context.logger,a.tracking.NS);var b=g.Dz();b&&a&&g.Lz(b,[a.Dj,a.sf])};
g.k.t_=function(){var a=g.Dz(),b=j5(this);a&&b&&g.Mz(a,[b.Dj])};
g.k.rU=function(a){var b=j5(this),c=g.Dz();this.j?a?(a=this.context.logger,m5(a,b.tracking.FE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Dj&&g.Nz(c,b.Dj)):(a=this.context.logger,m5(a,b.tracking.FE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.sf&&g.Nz(c,b.sf)):(a=this.context.logger,m5(a,b.tracking.FE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.sf&&g.Nz(c,this.sf))};g.v(k5,$4);k5.prototype.zA=function(){$4.prototype.zA.call(this);c2a(this)};
k5.prototype.show=function(){$4.prototype.show.call(this);var a=g.Dz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Lz(a,[g.wz(b.itct)])};
k5.prototype.hide=function(){$4.prototype.hide.call(this);var a=g.Dz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Mz(a,[g.wz(b.itct)])};g.v(l5,k5);
l5.prototype.show=function(){if(!this.isActive){k5.prototype.show.call(this);if(!this.J){g.ho(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u0430\u043d\u0430\u043b\u0430",src:a.image_url,width:a.image_width,height:a.image_height}});g.Kl(this.u,!1);var b=this.context.Y.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ga:["branding-img-container"]}):
this.createElement({F:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.ye();c&&(b=this.context.Y.K("html5_player_branding_button_killswitch")?this.u:b,a5(this,b,c,this.annotation.id,a.session_data));g2a(this,a);this.J=!0}g.Kl(this.element,!0);this.isActive=!0;this.u&&d2a(this,this.u)}};
l5.prototype.hide=function(){this.isActive&&(k5.prototype.hide.call(this),g.Kl(this.element,!1),this.isActive=!1)};
l5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k5.prototype.destroy.call(this)};g.v(i2a,k5);g.k=i2a.prototype;g.k.show=function(){this.isActive||(k5.prototype.show.call(this),this.Z||(k2a(this),this.Z=!0),g.Kl(this.element,!0),g.Qh(function(){g.jo(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,o2a(this),l2a(this),m2a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.ho(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.sF=function(a,b,c,d,e,f){return this.isCollapsed?!1:k5.prototype.sF.call(this,a,b,c,d,e,f)};
g.k.tZ=function(a){this.S=!0;j2a(this,500,a)};
g.k.sZ=function(){this.S=!1;n2a(this)};
g.k.nZ=function(a){a.stopPropagation();this.hide()};
g.k.oZ=function(a){a.stopPropagation();o2a(this);this.isCollapsed=!0;g.ho(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();k5.prototype.destroy.call(this)};g.v(q2a,g.fO);g.k=q2a.prototype;g.k.Cg=function(a,b){if(!D2a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.DXa(b))&&u2a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(S1a(this.j,b),E4(this.player)),!0}return null};
g.k.getOptions=function(){return D2a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Qt=function(){var a=this.player.V(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.dT||a.oa.get(b.videoId)||g.rI(b)||g.sI(b)?!0:!1};
g.k.ED=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Il(this.B.element,a.width,a.height);g.El(this.B.element,a.left,a.top)}if(this.j){var b=this.player.dk();a=this.j;b=b.width;g.lo(a.C,"iv-drawer-small",426>=b);g.lo(a.C,"iv-drawer-big",1280<=b)}};
g.k.tU=function(a){s2a(this,a.state);g.V(a.state,2)&&(this.zi()&&this.tm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Qw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.yu(h)&&h.responseXML?h.responseXML:null)&&(u2a(b,h),g.ho(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fO.prototype.load.call(this);s2a(this,this.player.Cb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Hv()&&(a=v2a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().oa.get(d);f&&w2a(e,f);f=f&&(f.RB||f.jy);if(!c.Wt||f)c.Ya?this.C=g.Eu(c.Ya,e):(this.En=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.En));
g.EN(this.player,this.B.element,4);this.ED();(f=g.rI(c))&&B2a(this,f);(f=g.sI(c))&&f.featuredChannel&&C2a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&(this.En&&(this.player.removeEventListener("videodatachange",this.En),this.En=null),this.C=g.Eu(b.Ya,a))};
g.k.unload=function(){this.player.Ff("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,E4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.fO.prototype.unload.call(this);this.B.detach();this.En&&(this.player.removeEventListener("videodatachange",this.En),this.En=null)};
g.k.xR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?x2a(this):this.load())};
g.k.zi=function(){return!!this.j&&this.j.isAvailable()};
g.k.tm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.zi();this.j&&(a?c?c5(this.j,c,b):c5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):d5(this.j))};
g.k.Qw=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().oa.unsubscribe("vast_info_card_add",this.xR,this);g.jo(this.player.getRootNode(),g.sT.IV_DRAWER_OPEN);for(var a=this.S,b=g.Vn,c=0,d=a.length;c<d;c++)b.Yk(a[c]);this.S.length=0;g.fO.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.eO("annotations_module",q2a);g.eO("creatorendscreen",k1a);})(_yt_player);
