(function(g){var window=this;'use strict';var D4a=function(a,b){a.Pa("onAutonavCoundownStarted",b)},m6=function(a,b,c){g.lo(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Nf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.XG&&(b.lengthText?(e=b.lengthText||null,f=b.Vs||null):b.lengthSeconds&&(e=g.$L(b.lengthSeconds),f=g.$L(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.VG(d).type;var l=b instanceof g.XG?b.isLivePlayback:null,m=b instanceof g.XG?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,u=[],w=[];n&&u.push(n);p&&(u.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:u.join(" \u2022 "),aria_label:b.ariaLabel||
g.KJ("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Mm(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.xp};b instanceof g.WG&&(c.playlist_length=b.playlistLength);a.update(c)},n6=function(a){var b=a.V(),c=b.u;
g.W.call(this,{F:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{F:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},
{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"},{F:"div",N:"ytp-autonav-list-overlay",W:[{F:"div",N:"ytp-autonav-mix-text",qa:"\u041c\u0438\u043a\u0441"},{F:"div",N:"ytp-autonav-mix-icon"}]}]},{F:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author",
"ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=null;this.j=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},o6=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{F:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.u=0;this.container=new g.W({F:"div",N:"ytp-autonav-endscreen-countdown-container"});g.M(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.u;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.W({F:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",N:"ytp-autonav-endscreen-upnext-header"},{F:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{F:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.J:""},W:[{F:"div",Ga:e,X:{style:"{{background}}"},W:[{F:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"}]},{F:"div",N:"ytp-autonav-endscreen-video-info",W:[{F:"div",N:"ytp-autonav-endscreen-premium-badge"},{F:"div",N:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{F:"div",N:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},
{F:"div",N:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},{F:"div",N:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.M(this,this.j);this.j.Ca(this.container.element);d||this.T(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.dM);this.G.ub(this.container.element,this,115127);this.G.ub(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({F:"div",N:"ytp-autonav-overlay"});g.M(this,this.overlay);this.overlay.Ca(this.container.element);
this.B=new g.W({F:"div",N:"ytp-autonav-endscreen-button-container"});g.M(this,this.B);this.B.Ca(this.container.element);this.cancelButton=new g.W({F:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.M(this,this.cancelButton);this.cancelButton.Ca(this.B.element);this.cancelButton.Ra("click",this.CU,this);this.G.ub(this.cancelButton.element,this,115129);this.playButton=new g.W({F:"a",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
qa:"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438"});g.M(this,this.playButton);this.playButton.Ca(this.B.element);this.playButton.Ra("click",this.dM,this);this.G.ub(this.playButton.element,this,115130);this.C=new g.Zn(function(){E4a(c)},500);
g.M(this,this.C);this.cM();this.T(a,"autonavvisibility",this.cM);this.G.K("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.BU),this.T(a,"onAutonavCoundownStarted",this.M0))},p6=function(a){var b=a.G.dk(!0,a.G.isFullscreen());
g.lo(a.container.element,"ytp-autonav-endscreen-small-mode",a.Ig(b));g.lo(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.BE);g.lo(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.bf());g.lo(a.G.getRootNode(),"countdown-running",a.rj());g.lo(a.container.element,"ytp-player-content",a.G.bf());g.yl(a.overlay.element,{width:b.width+"px"});if(!a.rj()){a.G.bf()?F4a(a,Math.round(G4a(a)/1E3)):F4a(a);b=!!a.suggestion&&!!a.suggestion.xp;var c=a.G.bf()||!b;
g.lo(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.lo(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.aL(a.B,a.G.bf());g.lo(a.element,"ytp-enable-w2w-color-transitions",H4a(a))}},E4a=function(a){var b=G4a(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);F4a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.rj()?a.select(!0):a.rj()&&a.C.start()},G4a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.lK;return-1===a||void 0===a?8E3:a}return 0<=a.G.Np()?a.G.Np():g.WE(a.G.V().experiments,"autoplay_time")||1E4},H4a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},F4a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.qh(a);if(0<=b){b=String(b);var c="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.ph("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.ih("span");g.fo(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.vh(e,b);a.appendChild(e);a.appendChild(g.ph("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.vh(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")},q6=function(a,b){g.W.call(this,{F:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},r6=function(a){g.W.call(this,{F:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{F:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-upnext-top",W:[{F:"span",N:"ytp-upnext-header",qa:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{F:"span",N:"ytp-upnext-title",qa:"{{title}}"},{F:"span",N:"ytp-upnext-author",qa:"{{author}}"}]},{F:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
W:[{F:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},W:[{F:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",N:"ytp-upnext-bottom",
W:[{F:"span",N:"ytp-upnext-cancel"},{F:"span",N:"ytp-upnext-paused",qa:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Zn(this.VB,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=
new g.W({F:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.M(this,this.cancelButton);this.cancelButton.Ra("click",this.DU,this);this.cancelButton.Ca(b);this.cancelButton&&this.api.ub(this.cancelButton.element,this,115129);g.M(this,this.C);this.api.ub(this.element,
this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.T(b,"click",this.EU);this.api.ub(b,this,115130);this.eM();this.T(a,"autonavvisibility",this.eM);this.T(a,"mdxnowautoplaying",this.K1);this.T(a,"mdxautoplaycanceled",this.L1);g.lo(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},I4a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.lK;return-1===a||void 0===a?8E3:a}return 0<=a.api.Np()?a.api.Np():g.WE(a.api.V().experiments,"autoplay_time")||1E4},J4a=function(a,b){b=I4a(a,b);
var c=Math,d=c.min;var e=(0,g.T)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.rj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.rj()&&a.j.start()},s6=function(a){q6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({F:"div",N:"ytp-suggestion-panel",W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0434\u0440\u0443\u0433\u0438\u0435 \u0432\u0438\u0434\u0435\u043e"}]});this.J=new g.W({F:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new o6(this.player);g.M(this,this.u);this.u.Ca(this.element);a.getVideoData().Me?this.j=this.u:
(this.j=new r6(a),g.EN(this.player,this.j.element,4),g.M(this,this.j));this.overlay=new g.W({F:"div",N:"ytp-autonav-overlay-cancelled-state"});g.M(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.aE(this);g.M(this,this.C);g.M(this,this.table);this.table.Ca(this.element);this.table.show();g.M(this,this.J);this.J.Ca(this.table.element);this.hide()},t6=function(a){var b=a.bf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},K4a=function(a){q6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({F:"div",N:"ytp-subscribe-card",W:[{F:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{F:"div",N:"ytp-subscribe-card-right",W:[{F:"div",N:"ytp-author-name",qa:"{{author}}"},{F:"div",N:"html5-subscribe-button-container"}]}]});g.M(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.jP("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",
null,!0,!1,b.Jk,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));this.T(a,"videodatachange",this.Ja);this.Ja();this.hide()},u6=function(a){var b=a.V(),c=g.eE||g.NF?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{F:"a",Ga:e,X:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{F:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-videowall-still-info",W:[{F:"span",N:"ytp-videowall-still-info-bg",W:[{F:"span",N:"ytp-videowall-still-info-content",X:c,W:[{F:"span",N:"ytp-videowall-still-info-title",qa:"{{title}}"},{F:"span",
N:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{F:"span",N:"ytp-videowall-still-info-live",qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{F:"span",N:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:[{F:"span",N:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{F:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{F:"span",qa:"{{playlist_length}}"},
")"]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],W:[{F:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{F:"span",N:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.aE(this);g.M(this,this.j);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Ci(this.element,this);this.onVideoDataChange()},v6=function(a){q6.call(this,
a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.S=null;this.u=new g.aE(this);g.M(this,this.u);this.Z=a.K("web_rounded_thumbnails");this.I=new g.Zn(function(){g.ho(b.element,"ytp-show-tiles")},0);
g.M(this,this.I);var c=new g.W({F:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},W:[g.fL()]});g.M(this,c);c.Ca(this.element);c.Ra("click",this.IU,this);this.table=new g.YK({F:"div",N:"ytp-endscreen-content"});g.M(this,this.table);this.table.Ca(this.element);c=new g.W({F:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},W:[g.gL()]});g.M(this,c);c.Ca(this.element);c.Ra("click",
this.HU,this);a.getVideoData().Me?this.j=new o6(a,!0):this.j=new r6(a);g.M(this,this.j);g.EN(this.player,this.j.element,4);a.ub(this.element,this,158789);this.hide()},w6=function(a){return g.FN(a.player)&&a.Yx()&&!a.C},L4a=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.DI(e)]},x6=function(a){var b=a.bf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},M4a=function(a,b){g.W.call(this,{F:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0441\u043d\u043e\u0432\u0430 \u043d\u0430 YouTube";b=156915;break;case 2:a="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube";b=156942;break;default:a="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube",
b=156942}this.update({message:a,content:a});this.G.ub(this.element,this,b);this.Ra("click",this.onClick);g.aL(this,!0)},y6=function(a){q6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new M4a(a,1);g.M(this,this.watchButton);this.watchButton.Ca(this.element);a.ub(this.element,this,156914);this.hide()},Q4a=function(a){g.fO.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.aE(this);g.M(this,this.listeners);this.env=a.V();var c;(null==(c=g.uN(a))?0:c.Ps())?this.endScreen=new y6(a):N4a(a)?(this.B=!0,O4a(this),this.j?this.endScreen=new s6(a):this.endScreen=new v6(this.player)):this.env.Ue?this.endScreen=new K4a(this.player):this.endScreen=new q6(this.player);g.M(this,this.endScreen);g.EN(this.player,this.endScreen.element,4);P4a(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,
this);this.listeners.T(a,g.wA("endscreen"),function(d){b.onCueRangeEnter(d)});
this.listeners.T(a,g.xA("endscreen"),function(d){b.onCueRangeExit(d)})},O4a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Kk&&a.u===b.Me)return!1;a.j=b.Kk;a.u=b.Me;return!0},N4a=function(a){a=a.V();
return!a.B&&a.Lc&&!a.Ue},P4a=function(a){a.player.Ff("endscreen");
var b=a.player.getVideoData();b=new g.uA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.uA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.qe([b,c])};
g.UO.prototype.yA=g.ba(30,function(a){this.UJ!==a&&(this.UJ=a,this.Cn())});
g.xN.prototype.Np=g.ba(4,function(){return this.app.Np()});
g.PX.prototype.Np=g.ba(3,function(){return this.getVideoData().HT});g.v(n6,g.W);n6.prototype.select=function(){(this.G.Ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ey||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.vb(this.element)};
n6.prototype.onClick=function(a){g.FO(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
n6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Jx(a)||(this.select(),g.Ix(a))}};g.v(o6,g.W);g.k=o6.prototype;g.k.fB=function(a){this.suggestion!==a&&(this.suggestion=a,m6(this.j,a),this.playButton.Oa("url",this.suggestion.Mm()),p6(this))};
g.k.rj=function(){return 0<this.u};
g.k.Zw=function(){this.rj()||(this.u=Date.now(),E4a(this),D4a(this.G,G4a(this)),g.lo(this.G.getRootNode(),"countdown-running",this.rj()))};
g.k.wt=function(){this.Xo();E4a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.vh(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")};
g.k.Xo=function(){this.rj()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Xo()};
g.k.dM=function(a){g.FO(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.vb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Xa(a,!0),this.G.vb(a)),this.select())};
g.k.CU=function(){this.G.vb(this.cancelButton.element);g.zN(this.G,!0);this.D&&this.G.Pa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.D6)?void 0:c.command};
g.k.M0=function(a){if(H4a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.kM(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.kM(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.kM(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.kM(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.kM(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.kM(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.lo(this.element,"ytp-w2w-animate",!0)}};
g.k.BU=function(a){this.G.K("web_autonav_color_transition")&&2!==a&&g.lo(this.element,"ytp-w2w-animate",!1)};
g.k.cM=function(){var a=this.G.bf();this.I&&this.rb!==a&&g.aL(this,a);p6(this);this.G.Xa(this.container.element,a);this.G.Xa(this.cancelButton.element,a);this.G.Xa(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Xa(this.playButton.element,a)};
g.k.Ig=function(a){return 400>a.width||459>a.height};g.v(q6,g.W);g.k=q6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Yx=function(){return!1};
g.k.bf=function(){return!1};
g.k.WP=function(){return!1};g.v(r6,g.W);g.k=r6.prototype;g.k.VB=function(){this.notification&&(this.C.stop(),this.yc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.fB=function(a){this.suggestion=a;m6(this,a,"hqdefault.jpg")};
g.k.eM=function(){g.aL(this,this.api.bf());this.api.Xa(this.element,this.api.bf());this.api.Xa(this.Da("ytp-upnext-autoplay-icon"),this.api.bf());this.cancelButton&&this.api.Xa(this.cancelButton.element,this.api.bf())};
g.k.T1=function(){window.focus();this.VB()};
g.k.Zw=function(a){var b=this;this.rj()||(g.Yx("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+this.suggestion.title),this.u=(0,g.T)(),this.j=new g.Zn(function(){J4a(b,a)},25),J4a(this,a),D4a(this.api,I4a(this,a)));
g.jo(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.rj=function(){return!!this.j};
g.k.wt=function(){this.Xo();this.u=(0,g.T)();J4a(this);g.ho(this.element,"ytp-upnext-autoplay-paused")};
g.k.Xo=function(){this.rj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.VB(),this.notification=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:this.suggestion.title,icon:this.suggestion.Nf()}),this.B=this.T(this.notification,"click",this.T1),this.C.start())}this.Xo();this.api.nextVideo(!1,
a)};
g.k.EU=function(a){!g.uh(this.cancelButton.element,g.Ex(a))&&g.FO(a,this.api)&&(this.api.bf()&&this.api.vb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.DU=function(){this.api.bf()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.zN(this.api,!0)};
g.k.K1=function(a){this.api.getPresentingPlayerType();this.show();this.Zw(a)};
g.k.L1=function(){this.api.getPresentingPlayerType();this.Xo();this.hide()};
g.k.ra=function(){this.Xo();this.VB();g.W.prototype.ra.call(this)};g.v(s6,q6);g.k=s6.prototype;g.k.create=function(){q6.prototype.create.call(this);this.C.T(this.player,"appresize",this.Cx);this.C.T(this.player,"onVideoAreaChange",this.Cx);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.fM);this.C.T(this.player,"autonavcancel",this.FU);this.onVideoDataChange()};
g.k.show=function(){q6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.zN(this.player,!1);g.FN(this.player)&&this.Yx()&&!this.B?(t6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Zw():3===this.videoData.autonavState&&this.j.wt()):(g.zN(this.player,!0),t6(this));this.Cx()};
g.k.hide=function(){q6.prototype.hide.call(this);this.j.wt();t6(this)};
g.k.Cx=function(){var a=this.player.dk(!0,this.player.isFullscreen());t6(this);p6(this.u);g.lo(this.element,"ytp-autonav-cancelled-small-mode",this.Ig(a));g.lo(this.element,"ytp-autonav-cancelled-tiny-mode",this.fD(a));g.lo(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.yl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.lo(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.DI(this.videoData);b&&(this.j.fB(b),this.j!==this.u&&this.u.fB(b));for(b=0;b<R4a.length;++b){var c=R4a[b];if(a&&a[c]){this.videos[b]=new n6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,m6(d,c));g.M(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.Cx()}};
g.k.fM=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Xo(),this.rb&&this.Cx()):(this.I=!0,this.bf()&&(2===a?this.j.Zw():3===a&&this.j.wt()))};
g.k.FU=function(a){a?this.fM(1):(this.B=null,this.I=!1)};
g.k.Yx=function(){return 1!==this.videoData.autonavState};
g.k.Ig=function(a){return(910>a.width||459>a.height)&&!this.fD(a)&&!(400>=a.width||360>=a.height)};
g.k.fD=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.bf=function(){return this.rb&&g.FN(this.player)&&this.Yx()&&!this.B};
var R4a=[1,3,2,4];g.v(K4a,q6);K4a.prototype.Ja=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Jk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(u6,g.W);u6.prototype.select=function(){(this.api.Ll(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ey||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.vb(this.element)};
u6.prototype.onClick=function(a){g.FO(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
u6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Jx(a)||(this.select(),g.Ix(a))}};
u6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.C?!1:b.u};g.v(v6,q6);g.k=v6.prototype;g.k.create=function(){q6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.In();this.u.T(this.player,"appresize",this.In);this.u.T(this.player,"onVideoAreaChange",this.In);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.tF);this.u.T(this.player,"autonavcancel",this.GU);a=this.videoData.autonavState;a!==this.S&&this.tF(a);this.u.T(this.element,"transitionend",this.t3)};
g.k.destroy=function(){g.dz(this.u);g.af(this.stills);this.stills=[];q6.prototype.destroy.call(this);g.jo(this.element,"ytp-show-tiles");this.I.stop();this.S=this.videoData.autonavState};
g.k.Yx=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.rb;q6.prototype.show.call(this);L4a(this);g.jo(this.element,"ytp-show-tiles");this.player.V().isMobile?g.ao(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.zN(this.player,!1);w6(this)?(x6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Zw():3===this.videoData.autonavState&&this.j.wt()):(g.zN(this.player,!0),x6(this));a!==this.rb&&
this.player.Xa(this.element,!0)};
g.k.hide=function(){var a=this.rb;q6.prototype.hide.call(this);this.j.wt();x6(this);a!==this.rb&&this.player.Xa(this.element,!1)};
g.k.t3=function(a){g.Ex(a)===this.element&&this.In()};
g.k.In=function(){var a=L4a(this);if(a.length){g.ho(this.element,"ytp-endscreen-paginate");var b=this.G.dk(!0,this.G.isFullscreen()),c=g.uN(this.G);c&&(c=c.Vf()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,u=f/2,w=c<=h-2&&p>=u*n,y=f<=l-2&&p>=q*n;if((q+1)/u*e/d>d/(q/(u+1)*e)&&y)p-=q*n,f+=2;else if(w)p-=u*n,c+=2;else if(y)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;g.Il(b,n,p);g.yl(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.fB(g.DI(this.videoData));this.j instanceof o6&&p6(this.j);g.lo(this.element,"ytp-endscreen-takeover",w6(this));x6(this);n+=4;p+=4;for(h=d=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>
l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.Hg(q+this.B,m),0!==w){u=this.stills[d];u||(u=new u6(this.player),this.stills[d]=u,b.appendChild(u.element));y=Math.floor(p*l/f);var A=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-y-4,D=Math.floor(n*(h+w)/c)-A-4;g.El(u.element,A,y);g.Il(u.element,D,B);g.yl(u.element,"transitionDelay",(l+h)/20+"s");g.lo(u.element,"ytp-videowall-still-mini",1===w);g.lo(u.element,"ytp-videowall-still-large",2<w);this.Z&&(w=Math.max(D,B),g.lo(u.element,"ytp-videowall-still-round-large",
256<=w),g.lo(u.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.lo(u.element,"ytp-videowall-still-round-small",96>=w));q=a[q];u.suggestion!==q&&(u.suggestion=q,w=u.api.V(),y=g.go(u.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",m6(u,q,y),g.PF(w)&&(y=q.Mm(),A={},w.Aa&&g.fN(A,w.loaderUrl),y=g.xi(y,g.eN(A,"emb_rel_end")),u.Oa("url",y)),(q=(q=q.sessionData)&&q.itct)&&u.api.Ck(u.element,q));d++}g.lo(this.element,"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=
d;a--)c=this.stills[a],g.sh(c.element),g.$e(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.In())};
g.k.HU=function(){this.B+=this.stills.length;this.In()};
g.k.IU=function(){this.B-=this.stills.length;this.In()};
g.k.WP=function(){return this.j.rj()};
g.k.tF=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Xo(),this.rb&&this.In()):(this.D=!0,this.rb&&w6(this)&&(2===a?this.j.Zw():3===a&&this.j.wt()))};
g.k.GU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Xa(this.stills[a].element,!0);this.tF(1)}else this.C=null,this.D=!1;this.In()};
g.k.bf=function(){return this.rb&&w6(this)};g.v(M4a,g.W);g.k=M4a.prototype;g.k.onClick=function(a){g.GO(this.getVideoUrl(),this.G,a);this.G.vb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.PF(b)||g.$F(b)){var c={};b.Aa&&g.PF(b)&&g.fN(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.eN(c,b);a=g.xi(a,c)}return a};
g.k.Xa=function(){this.G.Xa(this.element,this.rb&&this.Aa)};
g.k.show=function(){g.W.prototype.show.call(this);this.Xa()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.Xa()};
g.k.Wb=function(a){g.W.prototype.Wb.call(this,a);this.Xa()};g.v(y6,q6);y6.prototype.show=function(){if(3!==this.player.getPlayerState()){q6.prototype.show.call(this);var a;null==(a=g.uN(this.player))||a.yA(!0);this.player.Xa(this.element,!0);this.watchButton.Wb(!0)}};
y6.prototype.hide=function(){q6.prototype.hide.call(this);var a;null==(a=g.uN(this.player))||a.yA(!1);this.player.Xa(this.element,!1);this.watchButton.Wb(!1)};g.v(Q4a,g.fO);g.k=Q4a.prototype;g.k.Qt=function(){var a;if(null==(a=g.uN(this.player))?0:a.Ps())return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.DI(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!N4a(this.player)||c;c=a.Ug||g.$F(a.Sa);var d=this.player.Ly();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.bf=function(){return this.endScreen.bf()};
g.k.c_=function(){return this.bf()?this.endScreen.WP():!1};
g.k.ra=function(){this.player.Ff("endscreen");g.fO.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.tb().ke.get("heartbeat"),d=g.DI(a);!d||b.videoId!==d.videoId||a.AN?(this.player.Ll(b.videoId,void 0,void 0,!0,!0,b),c&&c.lD("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.fO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.fO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Qt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){P4a(this);this.B&&O4a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new s6(this.player):this.endScreen=new v6(this.player),g.M(this,this.endScreen),g.EN(this.player,this.endScreen.element,4))};g.eO("endscreen",Q4a);})(_yt_player);
